import"./assets/modulepreload-polyfill-3cfb730f.js";import{r as a,h as N,u as W,c as z,a as O,b as D}from"./assets/apple-books-logo-65c05625.js";import{e as p,f as B,i as G,g as V,o as F,s as K,a as Q,c as Y,u as J,d as X}from"./assets/vendor-695d5387.js";import{f as Z}from"./assets/config-905a1586.js";const k=document.getElementById("to-top-button");window.addEventListener("scroll",()=>{window.pageYOffset>100?k.classList.add("active"):k.classList.remove("active")});k.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});function E(){window.scrollTo({top:0,behavior:"smooth"})}const S=document.querySelector(".loader");function g(){S.classList.remove("hidden")}function u(){S.classList.add("hidden")}const y="https://books-backend.p.goit.global/books";async function ee(){const e=`${y}/category-list`;return(await p.get(e)).data}async function L(){const e=`${y}/top-books`;return(await p.get(e)).data}async function C(e){e=e.trim();const t={category:e},o=`${y}/category`;return(await p.get(o,{params:t})).data}async function $(e){e=e.trim();const t=`${y}/${e}`;return(await p.get(t)).data}let b;function te({_id:e,author:t,contributor:o,title:n,book_image:s,list_name:r}){return b=r,`<li class="book-li-item">
                <button type="button" class="book-item" id="${e}" aria-label="${n} ${o}">
                <div class="book-wrapper">
                <img class="book-img" src="${s}" alt="${n} ${o}">
                <div class="book-overlay">
                <p class="book-overlay-text">QUICK VIEW</p>
                </div>
                </div>
                <div class="book-info">
                <p class="book-info-title">${n}</p>
                <p class="book-info-author">${t}</p>
                </div>
                </button>
            </li>`}function oe({books:e}){const t=e.map(te).join("");return`<li class="book-item-home">
                    <h3 class="book-category-title">${b}</h3>
                    <ul class="books-category-list">`+t+`</ul>
                    <button class="button see-more-btn" data-js="${b}" aria-label="See more">SEE MORE</button>
                </li>`}function ne(e){return'<h2 class="books-home-title">Best Sellers <span class="books-home-title-span">Books</span></h2><ul class="books-home-list">'+e.map(oe).join("")+"</ul>"}function v(e){const t=ne(e);a.mainContainer.innerHTML=t}function l(e){B.error({title:"Error",message:e})}async function ae(){g();try{const e=await L();v(e)}catch(e){l(e)}u()}ae();const M=document.querySelector(".categories-list");function se(e){return`<li class="category-item"><button type="button" class="category-button" data-category="${e}" aria-label="${e}">${e}</button></li>`}function re(e){const o='<li class="category-item"><button type="button" class="category-button js-current-category" data-category="all categories" aria-label="all categories">All categories</button></li>'+e.map(se).join("");M.innerHTML=o}async function m(e){await document.querySelector(".js-current-category").classList.remove("js-current-category"),document.querySelector(`button[data-category="${e}"]`).classList.add("js-current-category")}async function ie(e){if(e.preventDefault(),e.target.classList.contains("category-button"))if(a.mainContainer.innerHTML="",m(e.target.dataset.category),e.target.dataset.category==="all categories"){try{const t=await L();g(),v(t),m(e.target.dataset.category),u()}catch(t){l(t)}return}else try{const t=await C(`${e.target.dataset.category}`);a.mainContainer.innerHTML=await I(`${e.target.dataset.category}`,t),m(e.target.dataset.category),u()}catch(t){l(t)}}async function I(e,t){const o=e.split(" ");return` 
    <h2 class="block_books-title"
  >${o.splice(0,o.length/2).join(" ")} <span class="block_books-colortitle">${o.splice(o.length/2,o.length).join(" ")}</span></h2> 
          <ul class="block_books-list">${await ce(t)}</ul>
          <button class="button all-categories_btn" data-js="All Categories" aria-label="All categories">All Categories</button>`}async function ce(e){return e.map(le).join("")}function le({author:e,book_image:t,title:o,description:n,_id:s,contributor:r}){return`<li class="book-li-item">
    <button type="button" class="book-item" id="${s}" aria-label="${o} ${r}">  
    <div class="books_wrapper"> 
    <img class="books_image" src="${t}"  alt="${n}" loading="lazy" width="335" height="485" /> 
    <div class="books_overlay"> 
    <p class="books_overlay-text">QUICK VIEW</p> 
    </div> 
    </div> 
    <div class="books_info">  
    <p class="books_info-title">${o}</p>  
    <p class="books_info-author">${e}</p>  
    </div>
    </button>
    </li>`}async function de(e){if(e.preventDefault(),e.target.classList.contains("see-more-btn")){E();const t=e.target.dataset.js;a.mainContainer.innerHTML="",g();try{const o=await C(`${t}`);a.mainContainer.insertAdjacentHTML("beforeend",await I(`${t}`,o)),m(`${t}`),u()}catch(o){l(o)}}else if(e.target.classList.contains("all-categories_btn")){E(),a.mainContainer.innerHTML="";try{const t=await L();g(),v(t),m("all categories"),u()}catch(t){l(t)}}}const T=document.querySelector(".js-search"),ue=document.querySelector(".search-city"),me=document.getElementById("js-info-weather-city"),ge=document.querySelector("p.forecast-text");T.addEventListener("submit",pe);async function pe(e){e.preventDefault();const t=e.target.elements.city.value.trim()||"";try{const o=await fe(t),n=o.location.country,s=o.current.condition.icon,r=o.current.temp_c,c=o.current.condition.text,i=`
                <h2 class="country-city-title">${n}, ${t}</h2>
                <img class="weather-city-image" src="${s}" alt="${c}">
                <p class="weather-city-info">Temp.: ${Math.floor(r)} &deg;C</p>
                <p class="weather-city-info">${c}</p>
        `;me.innerHTML=i,ge.textContent=ye(c),e.target.elements.city.value="",ue.blur()}catch(o){B.error({title:"Error",message:o.message})}T.reset()}async function fe(e){const t="https://api.weatherapi.com/v1";return await(await p.get(`${t}/current.json`,{params:{key:"14c56bddeab14583a6e164909231107",q:e,lang:"en"}})).data}function ye(e){const t="Rain taps softly, like music, setting the scene for books. Rainy days are cozy, perfect for getting lost in books",o="Snow falls gently, making reading by the fire even better. Snowy weather creates a peaceful setting for immersive reading sessions",n="Sunny days make reading outside under trees delightful. Sunlight makes reading enjoyable with its warm and bright rays",s="Any weather is book weather! Embrace reading anytime, anywhere",r="Soft light filters through the clouds, ideal for cozy reading. Cloudy days offer a calm atmosphere, perfect for uninterrupted reading";return e.toLowerCase().includes("cloudy")?r:e.toLowerCase().includes("rain")?t:e.toLowerCase().includes("snow")?o:e.toLowerCase().includes("sunny")?n:s}const he=()=>{const e={openModalBtn:document.querySelectorAll("[data-modal-open]"),closeModalBtn:document.querySelector("[data-modal-close]"),modal:document.querySelector("[data-modal]"),modalShopigListBtn:document.querySelector(".modal-pop-up-btn")};e.modalShopigListBtn.addEventListener("click",ke),e.openModalBtn.forEach(i=>{i.addEventListener("click",o)}),e.closeModalBtn.addEventListener("click",n),e.modal.addEventListener("click",t),document.addEventListener("keydown",s);function t(i){i.target===i.currentTarget&&n()}function o(){e.modal.classList.toggle("is-hidden"),e.modal.classList.toggle("is-open"),e.modal.classList.contains("is-hidden")?(document.body.classList.add("no-scroll"),document.addEventListener("keydown",s),e.closeModalBtn.addEventListener("click",n),e.modal.addEventListener("click",t)):(r(),c())}function n(){e.modal.classList.add("is-hidden"),r(),c()}function s(i){i.key==="Escape"&&n()}function r(){document.body.classList.remove("no-scroll")}function c(){e.openModalBtn.forEach(i=>{i.removeEventListener("click",o)}),e.closeModalBtn.removeEventListener("click",n),e.modal.removeEventListener("click",t),document.removeEventListener("keydown",s)}};async function ke(e){const t=e.target.previousElementSibling.previousElementSibling.firstElementChild.id,o=await $(t);N(o)}let h;a.booksContainer.addEventListener("click",be);async function be(e){if(h=e.target.closest(".book-item"),a.modalWindowContent.innerHTML="",h){a.modalWindow.classList.remove("is-hidden"),he();try{a.body.classList.add("no-scroll");let t=h.id,o=await $(t);ve(o)}catch(t){l(t)}}}function Le({book_image:e,contributor:t,description:o,_id:n,title:s,author:r,buy_links:c}){return`<img class="modal-img" src="${e}" alt="${s} ${t}" id="${n}" width="278" height="408">
            <div class="modal-img-description">
                <h2 class="modal-book-title">${s}</h2>
                <h3 class="modal-book-author">${r}</h3>
                <p class="modal-book-desc">${o}</p>
                <ul class="modal-shops">
                    <li class="modal-shop">
                        <a href="${c[0].url}" target="_blank" class="modal-shop-link">
                            <img class="amazon" src="${O}" alt="Shop Logo">
                        </a>

                    <li class="modal-shop">
                        <a href="${c[1].url}" target="_blank" class="modal-shop-link">
                            <img class="book-shop" src="${D}" alt="Shop Logo">
                        </a>
                </ul>
            </div>`}function ve(e){W(!z(e._id));const t=Le(e);a.modalWindowContent.insertAdjacentHTML("afterbegin",t)}G(Z);const d=V(),w=document.getElementById("email"),we=document.getElementById("user-name"),U=document.getElementById("password"),Ee=document.getElementById("quickstart-password-reset");function j(){if(d.currentUser)K(d);else{const e=w.value,t=U.value;if(e.length<4){alert("Please enter an email address.");return}if(t.length<4){alert("Please enter a password.");return}Q(d,e,t).catch(function(o){const n=o.code,s=o.message;alert(n==="auth/wrong-password"?"Wrong password.":s),console.log(o),a.signInButton.disabled=!1})}a.signInButton.disabled=!0}function q(){const e=w.value,t=U.value,o=we.value;if(e.length<4){alert("Please enter an email address.");return}if(t.length<4){alert("Please enter a password.");return}if(o.length<4){alert("Please enter a User name.");return}Y(d,e,t).then(n=>J(n.user,{displayName:o})).catch(function(n){const s=n.code,r=n.message;s=="auth/weak-password"?alert("The password is too weak."):alert(r),console.log(n)})}function Be(){const e=w.value;X(d,e).then(function(){alert("Password Reset Email Sent!")}).catch(function(t){const o=t.code,n=t.message;(o=="auth/invalid-email"||o=="auth/user-not-found")&&alert(n),console.log(t)})}F(d,function(e){if(e){const t=e.displayName;e.email,e.emailVerified,e.photoURL,e.isAnonymous,e.uid,e.providerData,a.signInButton.textContent="Sign out",a.headerSignInBtn.textContent=t}else a.headerSignInBtn.textContent="Sign in",a.signInButton.textContent="Sign in";a.signInButton.disabled=!1});Ee.addEventListener("click",Be,!1);const A=document.querySelector(".auth-pop-up-close-btn"),P=document.querySelector(".backdrop-auth-pop-up"),f=document.querySelector(".pop-up-sign-up-btn"),_=document.querySelector(".auth-pop-up"),x=document.querySelector(".controls-container");a.headerSignInBtn.addEventListener("click",Se);function Se(){P.classList.toggle("is-hidden"),A.addEventListener("click",H),f.addEventListener("click",R),a.signInButton.addEventListener("click",j,!1)}function H(){P.classList.toggle("is-hidden"),A.removeEventListener("click",H),f.removeEventListener("click",R),_.classList.remove("sign-up-mode"),f.textContent="SIGN UP",a.signInButton.textContent="SIGN IN",a.signUpButton.removeEventListener("click",q,!1),x.classList.remove("is-hidden"),a.signInButton.removeEventListener("click",j,!1)}function R(){_.classList.add("sign-up-mode"),f.textContent="SIGN IN",a.signInButton.textContent="SIGN UP",x.classList.add("is-hidden"),a.signUpButton.addEventListener("click",q,!1)}async function Ce(){g();try{const t=(await ee()).map(o=>o.list_name).toSorted();re(t)}catch(e){l(e)}u()}M.addEventListener("click",ie);a.mainContainer.addEventListener("click",de);Ce();
//# sourceMappingURL=commonHelpers2.js.map
