import"./assets/modulepreload-polyfill-3cfb730f.js";import{r as a,h as R,u as N,c as W,a as z,b as O}from"./assets/apple-books-logo-6b5bc3ab.js";import{e as p,f as S,i as D,g as G,o as V,s as F,a as K,c as Q,u as Y,d as J}from"./assets/vendor-695d5387.js";import{f as X}from"./assets/config-905a1586.js";const k=document.getElementById("to-top-button");window.addEventListener("scroll",()=>{window.pageYOffset>100?k.classList.add("active"):k.classList.remove("active")});k.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});function B(){window.scrollTo({top:0,behavior:"smooth"})}const C=document.querySelector(".loader");function g(){C.classList.remove("hidden")}function u(){C.classList.add("hidden")}const y="https://books-backend.p.goit.global/books";async function Z(){const e=`${y}/category-list`;return(await p.get(e)).data}async function L(){const e=`${y}/top-books`;return(await p.get(e)).data}async function $(e){e=e.trim();const t={category:e},o=`${y}/category`;return(await p.get(o,{params:t})).data}async function M(e){e=e.trim();const t=`${y}/${e}`;return(await p.get(t)).data}let b;function ee({_id:e,author:t,contributor:o,title:n,book_image:s,list_name:r}){return b=r,`<li class="book-li-item">
                <button type="button" class="book-item" id="${e}" aria-label="${n} ${o}">
                <div class="book-wrapper">
                <img class="book-img" src="${s}" alt="${n} ${o}">
                <div class="book-overlay">
                <p class="book-overlay-text">QUICK VIEW</p>
                </div>
                </div>
                <div class="book-info">
                <p class="book-info-title">${n}</p>
                <p class="book-info-author">${t}</p>
                </div>
                </button>
            </li>`}function te({books:e}){const t=e.map(ee).join("");return`<li class="book-item-home">
                    <h3 class="book-category-title">${b}</h3>
                    <ul class="books-category-list">`+t+`</ul>
                    <button class="button see-more-btn" data-js="${b}" aria-label="See more">SEE MORE</button>
                </li>`}function oe(e){return'<h2 class="books-home-title">Best Sellers <span class="books-home-title-span">Books</span></h2><ul class="books-home-list">'+e.map(te).join("")+"</ul>"}function v(e){const t=oe(e);a.mainContainer.innerHTML=t}function l(e){S.error({title:"Error",message:e})}async function ne(){g();try{const e=await L();v(e)}catch(e){l(e)}u()}ne();const I=document.querySelector(".categories-list");function ae(e){return`<li class="category-item"><button type="button" class="category-button" data-category="${e}" aria-label="${e}">${e}</button></li>`}function se(e){const o='<li class="category-item"><button type="button" class="category-button js-current-category" data-category="all categories" aria-label="all categories">All categories</button></li>'+e.map(ae).join("");I.innerHTML=o}async function m(e){await document.querySelector(".js-current-category").classList.remove("js-current-category"),document.querySelector(`button[data-category="${e}"]`).classList.add("js-current-category")}async function re(e){if(e.preventDefault(),e.target.classList.contains("category-button"))if(a.mainContainer.innerHTML="",m(e.target.dataset.category),e.target.dataset.category==="all categories"){try{const t=await L();g(),v(t),m(e.target.dataset.category),u()}catch(t){l(t)}return}else try{const t=await $(`${e.target.dataset.category}`);a.mainContainer.innerHTML=await T(`${e.target.dataset.category}`,t),m(e.target.dataset.category),u()}catch(t){l(t)}}async function T(e,t){const o=e.split(" ");return` 
    <h2 class="block_books-title"
  >${o.splice(0,o.length/2).join(" ")} <span class="block_books-colortitle">${o.splice(o.length/2,o.length).join(" ")}</span></h2> 
          <ul class="block_books-list">${await ie(t)}</ul>
          <button class="button all-categories_btn" data-js="All Categories" aria-label="All categories">All Categories</button>`}async function ie(e){return e.map(ce).join("")}function ce({author:e,book_image:t,title:o,description:n,_id:s,contributor:r}){return`<li class="book-li-item">
    <button type="button" class="book-item" id="${s}" aria-label="${o} ${r}">  
    <div class="books_wrapper"> 
    <img class="books_image" src="${t}"  alt="${n}" loading="lazy" width="335" height="485" /> 
    <div class="books_overlay"> 
    <p class="books_overlay-text">QUICK VIEW</p> 
    </div> 
    </div> 
    <div class="books_info">  
    <p class="books_info-title">${o}</p>  
    <p class="books_info-author">${e}</p>  
    </div>
    </button>
    </li>`}async function le(e){if(e.preventDefault(),e.target.classList.contains("see-more-btn")){B();const t=e.target.dataset.js;a.mainContainer.innerHTML="",g();try{const o=await $(`${t}`);a.mainContainer.insertAdjacentHTML("beforeend",await T(`${t}`,o)),m(`${t}`),u()}catch(o){l(o)}}else if(e.target.classList.contains("all-categories_btn")){B(),a.mainContainer.innerHTML="";try{const t=await L();g(),v(t),m("all categories"),u()}catch(t){l(t)}}}const U=document.querySelector(".js-search"),de=document.querySelector(".search-city"),ue=document.getElementById("js-info-weather-city"),me=document.querySelector("p.forecast-text");U.addEventListener("submit",ge);async function ge(e){e.preventDefault();const t=e.target.elements.city.value.trim()||"";try{const o=await pe(t),n=o.location.country,s=o.current.condition.icon,r=o.current.temp_c,c=o.current.condition.text,i=`
                <h2 class="country-city-title">${n}, ${t}</h2>
                <img class="weather-city-image" src="${s}" alt="${c}">
                <p class="weather-city-info">Temp.: ${Math.floor(r)} &deg;C</p>
                <p class="weather-city-info">${c}</p>
        `;ue.innerHTML=i,me.textContent=fe(c),e.target.elements.city.value="",de.blur()}catch(o){S.error({title:"Error",message:o.message})}U.reset()}async function pe(e){const t="https://api.weatherapi.com/v1";return await(await p.get(`${t}/current.json`,{params:{key:"14c56bddeab14583a6e164909231107",q:e,lang:"en"}})).data}function fe(e){const t="Rain taps softly, like music, setting the scene for books. Rainy days are cozy, perfect for getting lost in books",o="Snow falls gently, making reading by the fire even better. Snowy weather creates a peaceful setting for immersive reading sessions",n="Sunny days make reading outside under trees delightful. Sunlight makes reading enjoyable with its warm and bright rays",s="Any weather is book weather! Embrace reading anytime, anywhere",r="Soft light filters through the clouds, ideal for cozy reading. Cloudy days offer a calm atmosphere, perfect for uninterrupted reading";return e.toLowerCase().includes("cloudy")?r:e.toLowerCase().includes("rain")?t:e.toLowerCase().includes("snow")?o:e.toLowerCase().includes("sunny")?n:s}const ye=()=>{const e={openModalBtn:document.querySelectorAll("[data-modal-open]"),closeModalBtn:document.querySelector("[data-modal-close]"),modal:document.querySelector("[data-modal]"),modalShopigListBtn:document.querySelector(".modal-pop-up-btn")};e.modalShopigListBtn.addEventListener("click",he),e.openModalBtn.forEach(i=>{i.addEventListener("click",o)}),e.closeModalBtn.addEventListener("click",n),e.modal.addEventListener("click",t),document.addEventListener("keydown",s);function t(i){i.target===i.currentTarget&&n()}function o(){e.modal.classList.toggle("is-hidden"),e.modal.classList.toggle("is-open"),e.modal.classList.contains("is-hidden")?(document.body.classList.add("no-scroll"),document.addEventListener("keydown",s),e.closeModalBtn.addEventListener("click",n),e.modal.addEventListener("click",t)):(r(),c())}function n(){e.modal.classList.add("is-hidden"),r(),c()}function s(i){i.key==="Escape"&&n()}function r(){document.body.classList.remove("no-scroll")}function c(){e.openModalBtn.forEach(i=>{i.removeEventListener("click",o)}),e.closeModalBtn.removeEventListener("click",n),e.modal.removeEventListener("click",t),document.removeEventListener("keydown",s)}};async function he(e){const t=e.target.previousElementSibling.previousElementSibling.firstElementChild.id,o=await M(t);R(o)}let h;a.booksContainer.addEventListener("click",ke);async function ke(e){if(h=e.target.closest(".book-item"),a.modalWindowContent.innerHTML="",h){a.modalWindow.classList.remove("is-hidden"),ye();try{a.body.classList.add("no-scroll");let t=h.id,o=await M(t);Le(o)}catch(t){l(t)}}}function be({book_image:e,contributor:t,description:o,_id:n,title:s,author:r,buy_links:c}){return`<img class="modal-img" src="${e}" alt="${s} ${t}" id="${n}" width="278" height="408">
            <div class="modal-img-description">
                <h2 class="modal-book-title">${s}</h2>
                <h3 class="modal-book-author">${r}</h3>
                <p class="modal-book-desc">${o}</p>
                <ul class="modal-shops">
                    <li class="modal-shop">
                        <a href="${c[0].url}" target="_blank" class="modal-shop-link">
                            <img class="amazon" src="${z}" alt="Shop Logo">
                        </a>

                    <li class="modal-shop">
                        <a href="${c[1].url}" target="_blank" class="modal-shop-link">
                            <img class="book-shop" src="${O}" alt="Shop Logo">
                        </a>
                </ul>
            </div>`}function Le(e){N(!W(e._id));const t=be(e);a.modalWindowContent.insertAdjacentHTML("afterbegin",t)}D(X);const d=G(),w=document.getElementById("email"),ve=document.getElementById("user-name"),j=document.getElementById("password"),we=document.getElementById("quickstart-password-reset");function q(){if(d.currentUser)F(d);else{const e=w.value,t=j.value;if(e.length<4){alert("Please enter an email address.");return}if(t.length<4){alert("Please enter a password.");return}K(d,e,t).catch(function(o){const n=o.code,s=o.message;alert(n==="auth/wrong-password"?"Wrong password.":s),console.log(o),a.signInButton.disabled=!1})}a.signInButton.disabled=!0,E()}function A(){const e=w.value,t=j.value,o=ve.value;if(e.length<4){alert("Please enter an email address.");return}if(t.length<4){alert("Please enter a password.");return}if(o.length<4){alert("Please enter a User name.");return}Q(d,e,t).then(n=>Y(n.user,{displayName:o})).catch(function(n){const s=n.code,r=n.message;s=="auth/weak-password"?alert("The password is too weak."):alert(r),console.log(n)})}function Ee(){const e=w.value;J(d,e).then(function(){alert("Password Reset Email Sent!")}).catch(function(t){const o=t.code,n=t.message;(o=="auth/invalid-email"||o=="auth/user-not-found")&&alert(n),console.log(t)})}V(d,function(e){if(e){const t=e.displayName;e.email,e.emailVerified,e.photoURL,e.isAnonymous,e.uid,e.providerData,a.signInButton.textContent="Sign out",a.headerSignInBtn.textContent=t}else a.headerSignInBtn.textContent="Sign in",a.signInButton.textContent="Sign in";a.signInButton.disabled=!1});we.addEventListener("click",Ee,!1);const P=document.querySelector(".auth-pop-up-close-btn"),f=document.querySelector(".pop-up-sign-up-btn"),_=document.querySelector(".auth-pop-up"),x=document.querySelector(".controls-container");a.headerSignInBtn.addEventListener("click",Be);function Be(){a.authMenu.classList.toggle("is-hidden"),P.addEventListener("click",E),f.addEventListener("click",H),a.signInButton.addEventListener("click",q,!1)}function E(){a.authMenu.classList.toggle("is-hidden"),P.removeEventListener("click",E),f.removeEventListener("click",H),_.classList.remove("sign-up-mode"),f.textContent="SIGN UP",a.signInButton.textContent="SIGN IN",a.signUpButton.removeEventListener("click",A,!1),x.classList.remove("is-hidden"),a.signInButton.removeEventListener("click",q,!1)}function H(){_.classList.add("sign-up-mode"),f.textContent="SIGN IN",a.signInButton.textContent="SIGN UP",x.classList.add("is-hidden"),a.signUpButton.addEventListener("click",A,!1)}async function Se(){g();try{const t=(await Z()).map(o=>o.list_name).toSorted();se(t)}catch(e){l(e)}u()}I.addEventListener("click",re);a.mainContainer.addEventListener("click",le);Se();
//# sourceMappingURL=commonHelpers2.js.map
